### ISSUE TITLE
键盘盖合上再打开唤醒后触控板用不了

### ISSUE THREAD

**Issue by xwWang98** [molie34/Surface-Pro-6-macOS#26]
我试了下面的组合：
v2.0+新/旧版VoodooI2C，用不了；
v1.9.1+新版VoodooI2C，用不了；
更新前我是，v1.9.1+旧版VoodooI2C，原本可以用，但恢复回来就用不了了

**Comment by 9805xinwen** [comment]
还有几个问题：
1.通过长按电源键出来的重启选项只会关机，不会启动
2.每次键盘盖开盖唤醒前几秒输入密码，密码框会闪一下清空（密码还来不及输完），要重新输第二次

**Comment by Fnckerpoi** [comment]
目前我仍使用1.92，除了前面一个issues提及的hdmi输出没有音源和电量显示之外，目前各种状态体验良好，开机第二阶段logo确实花屏一下，但目前不太确定是否要更新2.0

**Comment by molie34** [comment]
试了确实有问题，需要拔掉键盘盖再插上才能唤醒触控板，目前还不知道具体哪个位置出错，初步判断是应该跟USB相关。

**Comment by Fnckerpoi** [comment]
不妨通过git的记录和1.92对校一下？

**Comment by zxb1030** [comment]
更新完也发现有问题，还有1.92版本的EFI下载吗？

**Comment by wangnengquan** [comment]
> 更新完也发现有问题，还有1.92版本的EFI下载吗？

![image](https://user-images.githubusercontent.com/22340549/56843429-33535c00-68d3-11e9-8667-907a651ba6cc.png)

点这个按钮不是想退哪个退哪个吗？

**Comment by molie34** [comment]
我会上传1.9.2的文件。

**Comment by molie34** [comment]
@Fnckerpoi 已经测试过几次版本，没有时间去忙对比了，你可以暂时保留在1.9.2，除非电量显示修复了才有必要更新。

**Comment by molie34** [comment]
@9805xinwen 真解决还的做代码修复，目前我根本没有那么时间去研究，目前能快速解决的就是用4919镜像重装一次系统。

**Comment by Fnckerpoi** [comment]
@molie34 好的，作者工作要紧，有闲时再弄，顺便请教一下作者从事哪方面领域？这种层面的工作一般都需要底层系统领域，计算机嵌入式汇编一类的么？

**Comment by 9805xinwen** [comment]
那就先这样用着把，不是什么大问题😂

**Comment by molie34** [comment]
@Fnckerpoi 现在刚成为自由职业。

**Comment by Fnckerpoi** [comment]
@molie34 有点猛
