### ISSUE TITLE
请问一下，有surface book的驱动吗

### ISSUE THREAD

**Issue by violin321** [molie34/Surface-Pro-6-macOS#28]
第一次尝试黑苹果，想看看有没有surface book一代的驱动

**Comment by Fnckerpoi** [comment]
没有，最初我买suface pro6之前也问过作者laptop2能不能装，最终我也选择了pro6

**Comment by molie34** [comment]
@violin321 surface book和Pro4 是一样的硬件方案，可以用Pro4 配置文件，如果还有细小差异就需要自己修复了。

**Comment by Fnckerpoi** [comment]
那请问一下laptop2是和pro6一样的么？

**Comment by molie34** [comment]
@Fnckerpoi 
我目前并没有接触过这个机器，但是从配置表上来看是同款处理器，除了分辨率没有Pro6高。同款处理器理论上是通用的，但是也可能存在一些细节差异需要修复。总之我初步判断这个laptop2机型黑起来也很相当简单。

**Comment by violin321** [comment]
恩恩，收到，昨晚我已经用pro4的efi加上你的clover安装了10.14.4,配置差不多的话，基本就是同理了，谢谢大佬~附上另一大佬的pro4 efi：https://github.com/Neil-Steven/SurfacePro4-Hackintosh/

**Comment by Fnckerpoi** [comment]
@molie34 如果是的话那我觉得laptop2的体验应该会更棒，我现在每次开机的适合都不得不使用原装键盘来选择进入系统，蓝牙键盘和触屏没办法在引导界面使用
