### ISSUE TITLE
No Graphics Acceleration

### ISSUE THREAD

**Issue by propane13omb** [molie34/Surface-Pro-6-macOS#43]
Hello,

Thank you very much for writing this tutorial, you're the first to do it!

I don't have access to Baidu as I live outside China. So I downloaded macos 10.14.1 and proceeded to make the install with that file. I used your efi, 1.9.2, 2.1 and even 2.2.

I can install, but then I can't boot with "config", only with "config-install", and I have no graphics acceleration because of this.

Please let me know if you can help.

**Comment by propane13omb** [comment]
Hey! Your images and tutorials have been deleted!!

**Comment by propane13omb** [comment]
The EFI is only compatible with 10.14.4, and not with any previous versions of macOs. Leaving this comment for anyone who has a similar problem but closing the issue.

**Comment by Sartharon** [comment]
Do you have a 10.14.4 iso? I build a 10.14.0 iso but that doesnt work as you say

**Comment by propane13omb** [comment]
> Do you have a 10.14.4 iso? I build a 10.14.0 iso but that doesnt work as you say

You can just download the 10.14.4 combo update from here: https://support.apple.com/kb/DL1996?locale=en_US

Apply the update, make sure to use "config-install" the whole way till you boot, then run kext-utility and reboot using "config"
