### ISSUE TITLE
官方的扩展坞能正常使用吗

### ISSUE THREAD

**Issue by rastaclat** [molie34/Surface-Pro-6-macOS#48]
在MacOS下官方的扩展坞能正常使用吗，谢谢

**Comment by jgb7886** [comment]
因为没有相应线材，所以视频输出没有测试，拓展坞的其他功能均正常

**Comment by rastaclat** [comment]
> 因为没有相应线材，所以视频输出没有测试，拓展坞的其他功能均正常

谢谢

**Comment by Fnckerpoi** [comment]
> 因为没有相应线材，所以视频输出没有测试，拓展坞的其他功能均正常

suface的拓展坞好像是有两个DP输出口，加上自身那个可以接上三个显示屏么？

**Comment by Elegantwolf** [comment]
手头pro4的拓展坞可以接单dp跟充电，但是USB不支持，双dp因为没有设备没法测试，希望能帮到你

**Comment by beyondskyway** [comment]
今天试了下，USB无线网卡正常，硬盘正常，充电正常。视频接口无法使用，插上就自动重启了
