### ISSUE TITLE
移动硬盘启动100%卡田字，有没有好点的解决办法

### ISSUE THREAD

**Issue by rastaclat** [molie34/Surface-Pro-6-macOS#49]
把MacOS做到了移动硬盘里面，每次启动都得卡田字，虽然强制关机再重启能解决这个问题，但是只能解决这次启动，重启之后还得强制关机来进入系统，每天如果重启好几次真的很麻烦，有没有一个好点的解决办法啊，谢谢了

**Comment by jgb7886** [comment]
我的设备是插着拓展坞或者插着USB2.0集线器开机的话就会99%卡田字（右下角有键盘符号的那个阶段），移除拓展坞或者集线器开机的话99%能正常进clover。
你可以试试先移除移动硬盘开机，进入clover后再插入移动硬盘看看？

**Comment by rastaclat** [comment]
> 我的设备是插着拓展坞或者插着USB2.0集线器开机的话就会99%卡田字（右下角有键盘符号的那个阶段），移除拓展坞或者集线器开机的话99%能正常进clover。
> 你可以试试先移除移动硬盘开机，进入clover后再插入移动硬盘看看？
谢谢，移除移动硬盘，开机等安全启动那个红条出现的时候再插入是能正常启动的，但是还是想找个能正常启动的方法。
我想把UEFI放电脑内置硬盘，然后用Clover来引导本机的win10以及移动硬盘上的黑苹果(目前这样没有卡田字)，但是这样进入clover引导界面只有win10没有黑苹果

**Comment by rastaclat** [comment]
> 我的设备是插着拓展坞或者插着USB2.0集线器开机的话就会99%卡田字（右下角有键盘符号的那个阶段），移除拓展坞或者集线器开机的话99%能正常进clover。
> 你可以试试先移除移动硬盘开机，进入clover后再插入移动硬盘看看？

谢谢，移除移动硬盘，开机等安全启动那个红条出现的时候再插入是能正常启动的，但是还是想找个能正常启动的方法。
我想把UEFI放电脑内置硬盘，然后用Clover来引导本机的win10以及移动硬盘上的黑苹果(目前这样没有卡田字)，但是这样进入clover引导界面只有win10没有黑苹果

**Comment by jgb7886** [comment]
> 我的设备是插着拓展坞或者插着USB2.0集线器开机的话就会99%卡田字（右下角有键盘符号的那个阶段），移除拓展坞或者集线器开机的话99%能正常进clover。
> 你可以试试先移除移动硬盘开机，进入clover后再插入移动硬盘看看？
> 
> 谢谢，移除移动硬盘，开机等安全启动那个红条出现的时候再插入是能正常启动的，但是还是想找个能正常启动的方法。
> 我想把UEFI放电脑内置硬盘，然后用Clover来引导本机的win10以及移动硬盘上的黑苹果(目前这样没有卡田字)，但是这样进入clover引导界面只有win10没有黑苹果

我的UEFI是在内置硬盘，然后之前偶然有一次在装黑苹果的时候，是先进入clover界面后再插入安装盘，clover会自动增加安装盘的启动项。虽然没有试过把黑苹果装在移动硬盘，但是按我这个经历推断，你的想法应该也是可行的。
另外我的机子只要开机过程中外接了拓展设备，极大概率卡红条的田字，所以怀疑是不是clover兼容的问题。不过我是小白，无法作具体分析。。。。

**Comment by rastaclat** [comment]
> 我的设备是插着拓展坞或者插着USB2.0集线器开机的话就会99%卡田字（右下角有键盘符号的那个阶段），移除拓展坞或者集线器开机的话99%能正常进clover。
> 你可以试试先移除移动硬盘开机，进入clover后再插入移动硬盘看看？
> 谢谢，移除移动硬盘，开机等安全启动那个红条出现的时候再插入是能正常启动的，但是还是想找个能正常启动的方法。
> 我想把UEFI放电脑内置硬盘，然后用Clover来引导本机的win10以及移动硬盘上的黑苹果(目前这样没有卡田字)，但是这样进入clover引导界面只有win10没有黑苹果
> 
> 我的UEFI是在内置硬盘，然后之前偶然有一次在装黑苹果的时候，是先进入clover界面后再插入安装盘，clover会自动增加安装盘的启动项。虽然没有试过把黑苹果装在移动硬盘，但是按我这个经历推断，你的想法应该也是可行的。
> 另外我的机子只要开机过程中外接了拓展设备，极大概率卡红条的田字，所以怀疑是不是clover兼容的问题。不过我是小白，无法作具体分析。。。。

还是很感谢你愿意帮助我，我再多试试，谢谢了

**Comment by rastaclat** [comment]
终于解决了，而且换了官方扩展坞后蓝牙和wifi没有干扰了，目前使用感还不错

**Comment by jgb7886** [comment]
> 终于解决了，而且换了官方扩展坞后蓝牙和wifi没有干扰了，目前使用感还不错

你是插着官方拓展坞开机也不会卡田字么？

**Comment by rastaclat** [comment]
> 终于解决了，而且换了官方扩展坞后蓝牙和wifi没有干扰了，目前使用感还不错
> 
> 你是插着官方拓展坞开机也不会卡田字么？

插着官方扩展坞也会卡田字，只是碰巧官方扩展坞到了试了下蓝牙和wifi

**Comment by sealevelsun** [comment]
> > 终于解决了，而且换了官方扩展坞后蓝牙和wifi没有干扰了，目前使用感还不错
> > 你是插着官方拓展坞开机也不会卡田字么？
> 
> 插着官方扩展坞也会卡田字，只是碰巧官方扩展坞到了试了下蓝牙和wifi

你们EFI用的2.2还是2.1？

**Comment by jgb7886** [comment]
> 终于解决了，而且换了官方扩展坞后蓝牙和wifi没有干扰了，目前使用感还不错
> 你是插着官方拓展坞开机也不会卡田字么？
> 
> 插着官方扩展坞也会卡田字，只是碰巧官方扩展坞到了试了下蓝牙和wifi
> 
> 你们EFI用的2.2还是2.1？

我是2.2的EFI，系统10.14.4

**Comment by rastaclat** [comment]
> > 终于解决了，而且换了官方扩展坞后蓝牙和wifi没有干扰了，目前使用感还不错
> > 你是插着官方拓展坞开机也不会卡田字么？
> 
> 插着官方扩展坞也会卡田字，只是碰巧官方扩展坞到了试了下蓝牙和wifi

2.2的EFI
