### ISSUE TITLE
大神有兴趣合作吗？

### ISSUE THREAD

**Issue by gnodipac886** [molie34/Surface-Pro-6-macOS#5]
你好，我是搞matebook黑苹果的，一直内屏无法解决，想和你合作，有兴趣的话可以给个联系方式吗？

我只要想解决matebook 的黑屏问题。
这个是我发布的。https://github.com/gnodipac886/MatebookXPro-hackintosh

抱歉，中文不太好。

Edit*: 我QQ: 1650173600 
谢谢

**Comment by gnodipac886** [comment]
@molie34 matebook 也是3：2 的屏幕，我用你的EFI 改了一下下就panic。跪求大神帮帮忙。。。

**Comment by molie34** [comment]
高分屏可以试试：
取消32DVMT补丁；
取消4K开启；
取消DP -> HDMI
不要限制输出端口;
打上禁用minStolenSize补丁，10.14.3和10.14.4是不通用的；
用0x12345678 显卡注入进入系统重建缓存（可以下载我配置的config-Install.Plist 文件），这个是关键！

**Comment by gnodipac886** [comment]
@molie34 我现在可以用外接显示器， 但是内屏还是黑屏怎么办？

**Comment by molie34** [comment]
@gnodipac886 MatebookXPro 我好像看到有人解决好内屏黑屏了，我一时也找不到这个帖子了。
如果是10.14.3系统可以试试：
配置config->kextsToPatch 只留10.14.3的minStolenSize补丁，禁用独显，
使用FB生成仿冒KBL、59160000平台，生成的补丁把<key>PciRoot(0x0)/Pci(0x2,0x0)</key> 修改为：<key>PciRoot(0)/Pci(0x2,0)</key>，然后通过外接显示器进入的系统重建缓存，在选择配置了10.14.3的minStolenSize补丁的config.plist 文件进入系统。

如果还不行就尝试修改显示器接口，实际上黑屏的时候已经是驱动了显卡，只是没有输出到的内屏通道。

**Comment by gnodipac886** [comment]
@molie34 嗯好的，我已经解决了，稍微复杂一点，跟HBR有关系，谢谢！
