### ISSUE TITLE
关于 10.14.6 无限重启的解决办法

### ISSUE THREAD

**Issue by thep0y** [molie34/Surface-Pro-6-macOS#54]
我在原作者 EFI2.2 的基础上添加了 10.14.6 的支持，已解决只能 config_install 进入， 而 config 却重启的问题。
用 Clover Configurator 挂载 EFI 分区，将 config.list 文件替换掉 EFI 分区的"EFI-CLOVER-OEM-UEFI" 文件夹下的同名文件即可。

**_另外，一定要记得重新生成一个序列号～～～～～～～～～_**

链接: https://pan.baidu.com/s/1Qe3ai4_xlK4hJmq_jvnPmA 提取码: fj3g

**Comment by gary1346aa** [comment]
升级成功了，想问问大神实际上做了哪些修改呢？

**Comment by thep0y** [comment]
> 升级成功了，想问问大神实际上做了哪些修改呢？

我可不是什么大神，只是简单地在 config 配置文件中加入几行支持 10.14.6 的代码而已

**Comment by T-feige** [comment]
好东西，升级10.14.6木有任何问题

就是有一点，Pro6黑苹果性能发挥比较差，主频一直被锁定在3GHz以下

**Comment by gary1346aa** [comment]
我也有观察到这个现象，所以Geekbench成绩甚至不如i5版的macbook pro 13

**Comment by Fnckerpoi** [comment]
请问新的config文件会不会外接显示屏就重启？

**Comment by DeeliN-uno** [comment]
这真的是好东西，炒鸡感谢

**Comment by thep0y** [comment]
> 好东西，升级10.14.6木有任何问题
> 
> 就是有一点，Pro6黑苹果性能发挥比较差，主频一直被锁定在3GHz以下

你好，能不能提供一下原win10的EFI目录？手贱删了，万分感谢！！

**Comment by thep0y** [comment]
> 这真的是好东西，炒鸡感谢

你好，能不能提供一下原win10的EFI目录？手贱删了，万分感谢！！

**Comment by Fnckerpoi** [comment]
链接: https://pan.baidu.com/s/1Fx9aKiWFLTcCmL03AM6dEg 提取码: ur4f 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by DeeliN-uno** [comment]
> 请问新的config文件会不会外接显示屏就重启？

我用DP转HDMI线，热插拔直接重启

**Comment by Kencow** [comment]
请问可以分享你的整个clover目录吗？我从10.14.4升级到10.14.6后，用你的config文件还是无限重启，已经用install进去重建缓存，也生成新的序列号，还是不行。

**Comment by thep0y** [comment]
> 键盘盖盖上再打开，键盘盖触摸板失灵，有办法解决吗？

没遇到过此问题，你可以试试将触摸板驱动提取出来放到clover的kext目录里，进config_install重新生成缓存

**Comment by Kencow** [comment]
> > 键盘盖盖上再打开，键盘盖触摸板失灵，有办法解决吗？
> 
> 没遇到过此问题，你可以试试将触摸板驱动提取出来放到clover的kext目录里，进config_install重新生成缓存

现在这个问题又暂时消失了，诡异的。

**Comment by Kencow** [comment]
> 好东西，升级10.14.6木有任何问题
> 
> 就是有一点，Pro6黑苹果性能发挥比较差，主频一直被锁定在3GHz以下



> 我也有观察到这个现象，所以Geekbench成绩甚至不如i5版的macbook pro 13，不知道有沒有解呢

把 PluginType 设成 false 试试，我的i5最高可以上到 3.4GHz。
