### ISSUE TITLE
关于 USB 无线网卡的问题

### ISSUE THREAD

**Issue by thep0y** [molie34/Surface-Pro-6-macOS#56]
网卡是 COMFAST CF-811AC

现在的情况是 2.4G 信道下有时能连接上但是无法上网，有时连接不上，具体情况如下：
- 能连接上的时候
   - “网络”里的“802.11ac NIC”为黄色，ip 地址为 169.254 开头，无法获取“路由器”和“DNS 服务器”，手动设定也无法联网
- 不能连接上的时候
   - 在记住密码的情况下，有时提示密码错误，有时许久连接不上。

在 5G 的信道下，一切正常。

使用的驱动为 **_RTLWlanU_MacOS10.9_MacOS10.14_Driver_1830.20.b35_1827.4.b33_UI_5.0.8.b5_**

另外，我的“以太网”是“已连接”的黄色状态，和 2.4G 信道下连接上无法联网一模一样，ip 地址 169.254.*.* 

不知这种情况该如何解决？

**Comment by VVMiao** [comment]
> 网卡是 COMFAST CF-811AC
> 
> 现在的情况是 2.4G 信道下有时能连接上但是无法上网，有时连接不上，具体情况如下：
> 
> * 能连接上的时候
>   
>   * “网络”里的“802.11ac NIC”为黄色，ip 地址为 169.254 开头，无法获取“路由器”和“DNS 服务器”，手动设定也无法联网
> * 不能连接上的时候
>   
>   * 在记住密码的情况下，有时提示密码错误，有时许久连接不上。
> 
> 在 5G 的信道下，一切正常。
> 
> 使用的驱动为 **_RTLWlanU_MacOS10.9_MacOS10.14_Driver_1830.20.b35_1827.4.b33_UI_5.0.8.b5_**
> 
> 另外，我的“以太网”是“已连接”的黄色状态，和 2.4G 信道下连接上无法联网一模一样，ip 地址 169.254._._
> 
> 不知这种情况该如何解决？

是否直接插surface的use 3.0接口？（不通过任何拓展坞）

**Comment by thep0y** [comment]
> > 网卡是 COMFAST CF-811AC
> > 现在的情况是 2.4G 信道下有时能连接上但是无法上网，有时连接不上，具体情况如下：
> > 
> > * 能连接上的时候
> >   
> >   * “网络”里的“802.11ac NIC”为黄色，ip 地址为 169.254 开头，无法获取“路由器”和“DNS 服务器”，手动设定也无法联网
> > * 不能连接上的时候
> >   
> >   * 在记住密码的情况下，有时提示密码错误，有时许久连接不上。
> > 
> > 在 5G 的信道下，一切正常。
> > 使用的驱动为 **_RTLWlanU_MacOS10.9_MacOS10.14_Driver_1830.20.b35_1827.4.b33_UI_5.0.8.b5_**
> > 另外，我的“以太网”是“已连接”的黄色状态，和 2.4G 信道下连接上无法联网一模一样，ip 地址 169.254._._
> > 不知这种情况该如何解决？
> 
> 是否直接插surface的use 3.0接口？（不通过任何拓展坞）

是有拓展坞的，和这个有关吗？

**Comment by thep0y** [comment]
> * 能

经过测试，直插 usb3.0 接口确实能解决这个问题啊，但是如果直插，那就啥也干不了了啊，请问有别的解决办法吗？

**Comment by VVMiao** [comment]
> > * 能
> 
> 经过测试，直插 usb3.0 接口确实能解决这个问题啊，但是如果直插，那就啥也干不了了啊，请问有别的解决办法吗？

自己认真看readme作者怎么说，去翻issue人家遇到这个问题时怎么做

**Comment by thep0y** [comment]
> > > * 能
> > 
> > 
> > 经过测试，直插 usb3.0 接口确实能解决这个问题啊，但是如果直插，那就啥也干不了了啊，请问有别的解决办法吗？
> 
> 自己认真看readme作者怎么说，去翻issue人家遇到这个问题时怎么做

虽然我并没有看见有别人遇到这个问题，但是经你提醒发现了 USB 网卡插在 hub 不同的接口能识别的 wifi 信道是不同的，非常感谢！

**Comment by Fnckerpoi** [comment]
> > > > * 能
> > > 
> > > 
> > > 经过测试，直插usb3.0接口确实能解决这个问题啊，但是如果直插，那就啥也干不了了啊，请问有别的解决办法吗？
> > 
> > 
> > 自己认真看自述作者怎么说，去翻问题人家遇到这个问题时怎么做
> 
> 虽然我并没有见见有别人遇到这个问题，但是经你提醒发现了USB网卡插在hub不同的接口能识别的wifi信道是不同的，非常感谢！

我第一个USB网卡也是这一款2.4G版本信号也是不稳定，经常连不上 自己断还会密码错误。我后来回店家了解似乎不是低功耗芯，所以我后面又买了一个双频的解决了所有问题

**Comment by Fnckerpoi** [comment]
> > > > > * 能
> > > > 
> > > > 
> > > > 经过测试，直插USB3.0接口确实能解决这个问题啊，但是如果直插，那就啥也干不了了啊，请问有别的解决办法吗？
> > > 
> > > 
> > > 自己认真看自述作者怎么说，去翻问题人家遇到这个问题时怎么做
> > 
> > 
> > 虽然我并没有见见有别人遇到这个问题，但是经你提醒发现了USB网卡插在轮毂不同的接口能识别的无线网络信道是不同的，非常感谢！
> 
> 我第一个USB网卡也是这一款2.4G版本信号也是不稳定，经常连不上自己断还会密码错误。我后来回店家了解似乎不是低功耗芯，所以我后面又买了一个双频的解决了所有问题

我也是用淘宝上的一个贴身hub拓展USB口，但是问题不大。可能是品控问题，因为一个USB口拓展出多个USB没有外供电源肯定是供电不足的。所以如果你是使用官方拓展坞应该没问题。如果有条件希望你可以试试最新四代拓展坞然后外接显示屏会不会有重启现象，因为我前天买了二手三代拓展坞，只有机身miniPD外接显示屏没有问题，一接拓展坞的miniDP就会重启。

**Comment by jgb7886** [comment]
> > > > > > * 能
> > > > > 
> > > > > 
> > > > > 经过测试，直插USB3.0接口确实能解决这个问题啊，但是如果直插，那就啥也干不了了啊，请问有别的解决办法吗？
> > > > 
> > > > 
> > > > 自己认真看自述作者怎么说，去翻问题人家遇到这个问题时怎么做
> > > 
> > > 
> > > 虽然我并没有见见有别人遇到这个问题，但是经你提醒发现了USB网卡插在轮毂不同的接口能识别的无线网络信道是不同的，非常感谢！
> > 
> > 
> > 我第一个USB网卡也是这一款2.4G版本信号也是不稳定，经常连不上自己断还会密码错误。我后来回店家了解似乎不是低功耗芯，所以我后面又买了一个双频的解决了所有问题
> 
> 我也是用淘宝上的一个贴身hub拓展USB口，但是问题不大。可能是品控问题，因为一个USB口拓展出多个USB没有外供电源肯定是供电不足的。所以如果你是使用官方拓展坞应该没问题。如果有条件希望你可以试试最新四代拓展坞然后外接显示屏会不会有重启现象，因为我前天买了二手三代拓展坞，只有机身miniPD外接显示屏没有问题，一接拓展坞的miniDP就会重启。

我怀疑是USB网卡本身的问题。我之前买的就是插在USB3.0集线器上完全无法连接2.4G频段，只能连接5G频段，但是通过USB2.0集线器或者直接插在surface上就没问题，以至于我怀疑是集线器的问题，于是后来换了3种集线器分别是两种芯片的，但是都无法解决。直到最后我把USB网卡申请换货，另换了一个给我，就完全正常了

**Comment by Fnckerpoi** [comment]
> > > > > > > * 能
> > > > > > 
> > > > > > 
> > > > > > 经过测试，直插USB3.0接口确实能解决这个问题啊，但是如果直插，那就啥也干不了了啊，请问有别的解决办法吗？
> > > > > 
> > > > > 
> > > > > 自己认真看自述作者怎么说，去翻问题人家遇到这个问题时怎么做
> > > > 
> > > > 
> > > > 虽然我并没有见见有别人遇到这个问题，但是经你提醒发现了USB网卡插在轮毂不同的接口能识别的无线网络信道是不同的，非常感谢！
> > > 
> > > 
> > > 我第一个USB网卡也是这一款2.4G版本信号也是不稳定，经常连不上自己断还会密码错误。我后来回店家了解似乎不是低功耗芯，所以我后面又买了一个双频的解决了所有问题
> > 
> > 
> > 我也是用淘宝上的一个贴身毂拓展USB口，但是问题不大。可能是品控问题，因为一个USB口拓展出多个USB没有外供电源肯定是供电不足的。所以如果你是使用官方拓展。坞应该没问题如果有条件希望你可以试试最新四代拓展坞然后外接显示屏会不会有重启现象，因为我前天买了二手三代拓展坞，只有机身miniPD外接显示屏没有问题，一接拓展坞的miniDP就会重启。
> 
> 我怀疑是USB网卡本身的问题。我之前买的就是插在USB3.0集线器上完全无法连接2.4G频段，只能连接5G频段，但是通过USB2.0集线器或者直接插在表面上就没问题，以至于我怀疑是集线器的问题，于是后来换了3种集线器分别是两种芯片的，但是都无法解决。直到最后我把USB网卡申请换货，另换了一个给我，就完全正常了

那基本就是品控问题了～

**Comment by thep0y** [comment]
> > > > > > > * 能
> > > > > > 
> > > > > > 
> > > > > > 经过测试，直插USB3.0接口确实能解决这个问题啊，但是如果直插，那就啥也干不了了啊，请问有别的解决办法吗？
> > > > > 
> > > > > 
> > > > > 自己认真看自述作者怎么说，去翻问题人家遇到这个问题时怎么做
> > > > 
> > > > 
> > > > 虽然我并没有见见有别人遇到这个问题，但是经你提醒发现了USB网卡插在轮毂不同的接口能识别的无线网络信道是不同的，非常感谢！
> > > 
> > > 
> > > 我第一个USB网卡也是这一款2.4G版本信号也是不稳定，经常连不上自己断还会密码错误。我后来回店家了解似乎不是低功耗芯，所以我后面又买了一个双频的解决了所有问题
> > 
> > 
> > 我也是用淘宝上的一个贴身hub拓展USB口，但是问题不大。可能是品控问题，因为一个USB口拓展出多个USB没有外供电源肯定是供电不足的。所以如果你是使用官方拓展坞应该没问题。如果有条件希望你可以试试最新四代拓展坞然后外接显示屏会不会有重启现象，因为我前天买了二手三代拓展坞，只有机身miniPD外接显示屏没有问题，一接拓展坞的miniDP就会重启。
> 
> 我怀疑是USB网卡本身的问题。我之前买的就是插在USB3.0集线器上完全无法连接2.4G频段，只能连接5G频段，但是通过USB2.0集线器或者直接插在surface上就没问题，以至于我怀疑是集线器的问题，于是后来换了3种集线器分别是两种芯片的，但是都无法解决。直到最后我把USB网卡申请换货，另换了一个给我，就完全正常了

请问你使用的网型号是？
