### ISSUE TITLE
问一下各位能正常使用 2.4G和 5G 无线网络的 usb 集线器型号和网卡型号

### ISSUE THREAD

**Issue by thep0y** [molie34/Surface-Pro-6-macOS#60]
usb 网卡已经换了一个了，但是2.4G 信道依旧上不了。
usb 3.0 集线器是带电源的，也一直连着电源。
刚换网卡的时候，某个usb 口本来可以连接 2.4G，但重启一次后就再也连不上了。
不知道具体是 usb 集线器的问题，还是网卡的问题。
所以很想知道能正常使用2.4G 网络的 usb网卡型号和 usb 集线器型号。

我的 usb 集线器： 京造 USB3.0 透明分线器
usb 网卡：COMFASE CF-812AC

**Comment by ReznovHuang** [comment]
CF-811AC表示2.4G 和5G 都是正常的，不过是直接插在机器上没有用集线器
另外不知道为啥我插着USB网卡重启就会卡田字，需要手动拔下来

**Comment by thep0y** [comment]
> CF-811AC表示2.4G 和5G 都是正常的，不过是直接插在机器上没有用集线器
> 另外不知道为啥我插着USB网卡重启就会卡田字，需要手动拔下来

不用集线器的话，确实能正常使用，但是就那么一个usb口，只用来上网，太浪费了吧

**Comment by ReznovHuang** [comment]
> > CF-811AC表示2.4G 和5G 都是正常的，不过是直接插在机器上没有用集线器
> > 另外不知道为啥我插着USB网卡重启就会卡田字，需要手动拔下来
> 
> 不用集线器的话，确实能正常使用，但是就那么一个usb口，只用来上网，太浪费了吧

是，最近也在物色合适的USB hub

**Comment by thep0y** [comment]
> > > CF-811AC表示2.4G 和5G 都是正常的，不过是直接插在机器上没有用集线器
> > > 另外不知道为啥我插着USB网卡重启就会卡田字，需要手动拔下来
> > 
> > 
> > 不用集线器的话，确实能正常使用，但是就那么一个usb口，只用来上网，太浪费了吧
> 
> 是，最近也在物色合适的USB hub

如果你能找到2.4G和5G都能用的，请告知一下。
目前我一直使用5G上网，而且在mac下网速要比windows差了2到3倍。
