### ISSUE TITLE
来留下你为了黑苹果而购置的正在使用的外设吧

### ISSUE THREAD

**Issue by thep0y** [molie34/Surface-Pro-6-macOS#78]
**目前遇到的问题和解决办法**
- 我现在使用的不知道是集线器原因，还是无线网卡的原因，也有可能是网卡驱动的原因，wifi只有5G能正常联网，2.4G能连上wifi，但不能正确分配ip地址，所以无法上网。
    - 解决办法：尚未解决。
- USB无线网卡会干扰USB蓝牙适配器信号，导致蓝牙键盘和鼠标会出现卡顿、连击等情况。
    - 解决方法：USB无线网卡插在1号(顺时针排序)口，蓝牙适配器放在3号口，移动硬盘放在2或4号口，能缓解这种信道干扰。

**外设型号**
- USB3.0集线器
    - 京东京造 USB3.0透明分线器(个人觉得颜值很高)
        - surface pro 6的电源上有个usb接口，而这个集线器供电口是MicroUSB，所以我就直接拿了根MicroUSB数据线连接二者了，集线器也就有了电源供电，很方便。
    - ![image](https://raw.githubusercontent.com/thep0y/Surface-Pro-6-macOS/master/images/usb分线器.jpg)
- USB无线网卡
    - COMFAST CF-812AC
    - 驱动为：RTLWlanU_MacOS10.9_MacOS10.13_Driver_1830.20.b15_1827.4.b29_UI_5.0.7（我的配置，只有这个驱动正常使用5Gwifi，无法同时使用5G和2.4G）
- USB蓝牙适配器
    - 绿联 USB蓝牙适配器 黑 30524
- 鼠标
    - 罗技 pebble
- 键盘
    - ANNE PRO2  box红轴 白色(强烈推荐box白轴，正准备再入一个box白轴) 

**请那些已使用外接屏幕的朋友留下你们的宝贵经验，因为我下一步就要增加外接屏了，不想走弯路。。。**

**11月30日更新**
今天才发现，我的USB无线网卡和蓝牙均虽然插在USB3.0的集线器上，但系统识别的是用的USB2.0的Hub，不知道能阅读此issue的朋友是否有相同情况，如图：
![image](https://raw.githubusercontent.com/thep0y/Surface-Pro-6-macOS/master/images/usb连接状态.png)

**Comment by Fnckerpoi** [comment]
- USB3.0集线器
      suface三代拓展坞 淘宝二手只要两百多，成色很不错8成新也没有磕磕碰碰就是边边角角有掉漆而已
      三个USB3.0+两个2.0
      100兆以太网网口  miniDP输出
      因为外接供电，外接U盘网卡蓝牙没有问题供电充足。但是DP口一接上就会黑屏重启
      原因未明
- 优联USB3.0转HDMI
      能用但是流畅度体验只有24帧感受。
      原因：因为拓展坞的miniDP口无法使用，出于对双屏的需求，所以只好采取这个方案
-蓝牙
      用的是淘宝一直在卖的那款免驱的，但是感觉还是差了点，连上三台设备，特别耳机会断音。
      也考虑绿联的那一款，听说不错。希望楼主试一下负荷测试
-鼠标
       雷柏的MT750s 四模和二代妙控板
       经测试连上ipadpro无法使用
-键盘 
       RK速写 和二代苹果的蓝牙键盘

**Comment by thep0y** [comment]
> * USB3.0集线器
>   suface三代拓展坞 淘宝二手只要两百多，成色很不错8成新也没有磕磕碰碰就是边边角角有掉漆而已
>   三个USB3.0+两个2.0
>   100兆以太网网口  miniDP输出
>   因为外接供电，外接U盘网卡蓝牙没有问题供电充足。但是DP口一接上就会黑屏重启
>   原因未明
> * 优联USB3.0转HDMI
>   能用但是流畅度体验只有24帧感受。
>   原因：因为拓展坞的miniDP口无法使用，出于对双屏的需求，所以只好采取这个方案
>   -蓝牙
>   用的是淘宝一直在卖的那款免驱的，但是感觉还是差了点，连上三台设备，特别耳机会断音。
>   也考虑绿联的那一款，听说不错。希望楼主试一下负荷测试
>   -鼠标
>   雷柏的MT750s 四模和二代妙控板
>   经测试连上ipadpro无法使用
>   -键盘
>   RK速写 和二代苹果的蓝牙键盘

USB3.0转HDMI怎么会这么差，什么原因呢？我正准备试试USB3.0转HDMI呢

**Comment by thep0y** [comment]
> * USB3.0集线器
>   suface三代拓展坞 淘宝二手只要两百多，成色很不错8成新也没有磕磕碰碰就是边边角角有掉漆而已
>   三个USB3.0+两个2.0
>   100兆以太网网口  miniDP输出
>   因为外接供电，外接U盘网卡蓝牙没有问题供电充足。但是DP口一接上就会黑屏重启
>   原因未明
> * 优联USB3.0转HDMI
>   能用但是流畅度体验只有24帧感受。
>   原因：因为拓展坞的miniDP口无法使用，出于对双屏的需求，所以只好采取这个方案
>   -蓝牙
>   用的是淘宝一直在卖的那款免驱的，但是感觉还是差了点，连上三台设备，特别耳机会断音。
>   也考虑绿联的那一款，听说不错。希望楼主试一下负荷测试
>   -鼠标
>   雷柏的MT750s 四模和二代妙控板
>   经测试连上ipadpro无法使用
>   -键盘
>   RK速写 和二代苹果的蓝牙键盘

今天刚上传了我的系统报告里的usb使用情况，你的也是这样吗？无线和蓝牙走的是usb2.0吗？

**Comment by Fnckerpoi** [comment]
> > * USB3.0集线器
> >   suface三代拓展坞 淘宝二手只要两百多，成色很不错8成新也没有磕磕碰碰就是边边角角有掉漆而已
> >   三个USB3.0+两个2.0
> >   100兆以太网网口  miniDP输出
> >   因为外接供电，外接U盘网卡蓝牙没有问题供电充足。但是DP口一接上就会黑屏重启
> >   原因未明
> > * 优联USB3.0转HDMI
> >   能用但是流畅度体验只有24帧感受。
> >   原因：因为拓展坞的miniDP口无法使用，出于对双屏的需求，所以只好采取这个方案
> >   -蓝牙
> >   用的是淘宝一直在卖的那款免驱的，但是感觉还是差了点，连上三台设备，特别耳机会断音。
> >   也考虑绿联的那一款，听说不错。希望楼主试一下负荷测试
> >   -鼠标
> >   雷柏的MT750s 四模和二代妙控板
> >   经测试连上ipadpro无法使用
> >   -键盘
> >   RK速写 和二代苹果的蓝牙键盘
> 
> 今天刚上传了我的系统报告里的usb使用情况，你的也是这样吗？无线和蓝牙走的是usb2.0吗？

不太清楚 但是报告里面我看他的传输速度只有12M每秒的显示
![Uploading image.png…]()

**Comment by Fnckerpoi** [comment]
> > * USB3.0集线器
> >   suface三代拓展坞 淘宝二手只要两百多，成色很不错8成新也没有磕磕碰碰就是边边角角有掉漆而已
> >   三个USB3.0+两个2.0
> >   100兆以太网网口  miniDP输出
> >   因为外接供电，外接U盘网卡蓝牙没有问题供电充足。但是DP口一接上就会黑屏重启
> >   原因未明
> > * 优联USB3.0转HDMI
> >   能用但是流畅度体验只有24帧感受。
> >   原因：因为拓展坞的miniDP口无法使用，出于对双屏的需求，所以只好采取这个方案
> >   -蓝牙
> >   用的是淘宝一直在卖的那款免驱的，但是感觉还是差了点，连上三台设备，特别耳机会断音。
> >   也考虑绿联的那一款，听说不错。希望楼主试一下负荷测试
> >   -鼠标
> >   雷柏的MT750s 四模和二代妙控板
> >   经测试连上ipadpro无法使用
> >   -键盘
> >   RK速写 和二代苹果的蓝牙键盘
> 
> 今天刚上传了我的系统报告里的usb使用情况，你的也是这样吗？无线和蓝牙走的是usb2.0吗？

然而我把它插在机身上的usb也没有多大流畅。鼠标还是有残影。但是线没有问题 因为我插在MBA上流畅度和hdmi没太大差距

**Comment by Fnckerpoi** [comment]
> **目前遇到的问题和解决办法**
> 
> * 我现在使用的不知道是集线器原因，还是无线网卡的原因，也有可能是网卡驱动的原因，wifi只有5G能正常联网，2.4G能连上wifi，但不能正确分配ip地址，所以无法上网。
>   
>   * 解决办法：尚未解决。
> * USB无线网卡会干扰USB蓝牙适配器信号，导致蓝牙键盘和鼠标会出现卡顿、连击等情况。
>   
>   * 解决方法：USB无线网卡插在1号(顺时针排序)口，蓝牙适配器放在3号口，移动硬盘放在2或4号口，能缓解这种信道干扰。
> 
> **外设型号**
> 
> * USB3.0集线器
>   
>   * 京东京造 USB3.0透明分线器(个人觉得颜值很高)
>     
>     * surface pro 6的电源上有个usb接口，而这个集线器供电口是MicroUSB，所以我就直接拿了根MicroUSB数据线连接二者了，集线器也就有了电源供电，很方便。
>   * ![image](https://raw.githubusercontent.com/thep0y/Surface-Pro-6-macOS/master/images/usb%E5%88%86%E7%BA%BF%E5%99%A8.jpg)
> * USB无线网卡
>   
>   * COMFAST CF-812AC
>   * 驱动为：RTLWlanU_MacOS10.9_MacOS10.13_Driver_1830.20.b15_1827.4.b29_UI_5.0.7（我的配置，只有这个驱动正常使用5Gwifi，无法同时使用5G和2.4G）
> * USB蓝牙适配器
>   
>   * 绿联 USB蓝牙适配器 黑 30524
> * 鼠标
>   
>   * 罗技 pebble
> * 键盘
>   
>   * ANNE PRO2  box红轴 白色(强烈推荐box白轴，正准备再入一个box白轴)
> 
> **请那些已使用外接屏幕的朋友留下你们的宝贵经验，因为我下一步就要增加外接屏了，不想走弯路。。。**
> 
> **11月30日更新**
> 今天才发现，我的USB无线网卡和蓝牙均虽然插在USB3.0的集线器上，但系统识别的是用的USB2.0的Hub，不知道能阅读此issue的朋友是否有相同情况，如图：
> ![image](https://raw.githubusercontent.com/thep0y/Surface-Pro-6-macOS/master/images/usb%E8%BF%9E%E6%8E%A5%E7%8A%B6%E6%80%81.png)

恰恰相反，我想从两个显示器减回到一个。mac不像window。外接一个显示屏就能管理好窗口了

**Comment by thep0y** [comment]
> > **目前遇到的问题和解决办法**
> > 
> > * 我现在使用的不知道是集线器原因，还是无线网卡的原因，也有可能是网卡驱动的原因，wifi只有5G能正常联网，2.4G能连上wifi，但不能正确分配ip地址，所以无法上网。
> >   
> >   * 解决办法：尚未解决。
> > * USB无线网卡会干扰USB蓝牙适配器信号，导致蓝牙键盘和鼠标会出现卡顿、连击等情况。
> >   
> >   * 解决方法：USB无线网卡插在1号(顺时针排序)口，蓝牙适配器放在3号口，移动硬盘放在2或4号口，能缓解这种信道干扰。
> > 
> > **外设型号**
> > 
> > * USB3.0集线器
> >   
> >   * 京东京造 USB3.0透明分线器(个人觉得颜值很高)
> >     
> >     * surface pro 6的电源上有个usb接口，而这个集线器供电口是MicroUSB，所以我就直接拿了根MicroUSB数据线连接二者了，集线器也就有了电源供电，很方便。
> >   * ![image](https://raw.githubusercontent.com/thep0y/Surface-Pro-6-macOS/master/images/usb%E5%88%86%E7%BA%BF%E5%99%A8.jpg)
> > * USB无线网卡
> >   
> >   * COMFAST CF-812AC
> >   * 驱动为：RTLWlanU_MacOS10.9_MacOS10.13_Driver_1830.20.b15_1827.4.b29_UI_5.0.7（我的配置，只有这个驱动正常使用5Gwifi，无法同时使用5G和2.4G）
> > * USB蓝牙适配器
> >   
> >   * 绿联 USB蓝牙适配器 黑 30524
> > * 鼠标
> >   
> >   * 罗技 pebble
> > * 键盘
> >   
> >   * ANNE PRO2  box红轴 白色(强烈推荐box白轴，正准备再入一个box白轴)
> > 
> > **请那些已使用外接屏幕的朋友留下你们的宝贵经验，因为我下一步就要增加外接屏了，不想走弯路。。。**
> > **11月30日更新**
> > 今天才发现，我的USB无线网卡和蓝牙均虽然插在USB3.0的集线器上，但系统识别的是用的USB2.0的Hub，不知道能阅读此issue的朋友是否有相同情况，如图：
> > ![image](https://raw.githubusercontent.com/thep0y/Surface-Pro-6-macOS/master/images/usb%E8%BF%9E%E6%8E%A5%E7%8A%B6%E6%80%81.png)
> 
> 恰恰相反，我想从两个显示器减回到一个。mac不像window。外接一个显示屏就能管理好窗口了

Mac需要的是一个大屏，pro6这种小屏非常影响使用体验。多窗口下太难用了，太小了。

**Comment by Fnckerpoi** [comment]
> > > **目前遇到的问题和解决办法**
> > > 
> > > * 我现在使用的不知道是集线器原因，还是无线网卡的原因，也有可能是网卡驱动的原因，wifi只有5G能正常联网，2.4G能连上wifi，但不能正确分配ip地址，所以无法上网。
> > >   
> > >   * 解决办法：尚未解决。
> > > * USB无线网卡会干扰USB蓝牙适配器信号，导致蓝牙键盘和鼠标会出现卡顿、连击等情况。
> > >   
> > >   * 解决方法：USB无线网卡插在1号(顺时针排序)口，蓝牙适配器放在3号口，移动硬盘放在2或4号口，能缓解这种信道干扰。
> > > 
> > > **外设型号**
> > > 
> > > * USB3.0集线器
> > >   
> > >   * 京东京造 USB3.0透明分线器(个人觉得颜值很高)
> > >     
> > >     * surface pro 6的电源上有个usb接口，而这个集线器供电口是MicroUSB，所以我就直接拿了根MicroUSB数据线连接二者了，集线器也就有了电源供电，很方便。
> > >   * ![image](https://raw.githubusercontent.com/thep0y/Surface-Pro-6-macOS/master/images/usb%E5%88%86%E7%BA%BF%E5%99%A8.jpg)
> > > * USB无线网卡
> > >   
> > >   * COMFAST CF-812AC
> > >   * 驱动为：RTLWlanU_MacOS10.9_MacOS10.13_Driver_1830.20.b15_1827.4.b29_UI_5.0.7（我的配置，只有这个驱动正常使用5Gwifi，无法同时使用5G和2.4G）
> > > * USB蓝牙适配器
> > >   
> > >   * 绿联 USB蓝牙适配器 黑 30524
> > > * 鼠标
> > >   
> > >   * 罗技 pebble
> > > * 键盘
> > >   
> > >   * ANNE PRO2  box红轴 白色(强烈推荐box白轴，正准备再入一个box白轴)
> > > 
> > > **请那些已使用外接屏幕的朋友留下你们的宝贵经验，因为我下一步就要增加外接屏了，不想走弯路。。。**
> > > **11月30日更新**
> > > 今天才发现，我的USB无线网卡和蓝牙均虽然插在USB3.0的集线器上，但系统识别的是用的USB2.0的Hub，不知道能阅读此issue的朋友是否有相同情况，如图：
> > > ![image](https://raw.githubusercontent.com/thep0y/Surface-Pro-6-macOS/master/images/usb%E8%BF%9E%E6%8E%A5%E7%8A%B6%E6%80%81.png)
> > 
> > 
> > 恰恰相反，我想从两个显示器减回到一个。mac不像window。外接一个显示屏就能管理好窗口了
> 
> Mac需要的是一个大屏，pro6这种小屏非常影响使用体验。多窗口下太难用了，太小了。

我是接了两个24寸屏幕，现在发现体验并没有多大提升。所以我觉得减回一个外接屏去了

**Comment by Fnckerpoi** [comment]
请问你的那款绿联蓝牙的驱动是怎么解决的？淘宝店家都分分说这款不支持mac，请问是免驱的吗

**Comment by thep0y** [comment]
> 请问你的那款绿联蓝牙的驱动是怎么解决的？淘宝店家都分分说这款不支持mac，请问是免驱的吗

我是在京东随便买的，当时想着不能用就退了呗，反正7天无理由，然后到手发现用得很不错

**Comment by Fnckerpoi** [comment]
> > 请问你的那款绿联蓝牙的驱动是怎么解决的？淘宝店家都分分说这款不支持mac，请问是免驱的吗
> 
> 我是在京东随便买的，当时想着不能用就退了呗，反正7天无理由，然后到手发现用得很不错

就是直接就是免驱的吗？

**Comment by thep0y** [comment]
> > > 请问你的那款绿联蓝牙的驱动是怎么解决的？淘宝店家都分分说这款不支持mac，请问是免驱的吗
> > 
> > 
> > 我是在京东随便买的，当时想着不能用就退了呗，反正7天无理由，然后到手发现用得很不错
> 
> 就是直接就是免驱的吗？

免驱

**Comment by Fnckerpoi** [comment]
> > > > 请问你的那款绿联蓝牙的驱动是怎么解决的？淘宝店家都分分说这款不支持mac，请问是免驱的吗
> > > 
> > > 
> > > 我是在京东随便买的，当时想着不能用就退了呗，反正7天无理由，然后到手发现用得很不错
> > 
> > 
> > 就是直接就是免驱的吗？
> 
> 免驱

谢了老哥，我那个CINSING用了好几个月，基本两个设备就上限了。除非用触控板还好一点，鼠标一动耳机声音就没了。我不知道为什么后来重启再看USB的传输速度又回到3.0的5G/S了

**Comment by bimbims** [comment]
Wifi USB dongle TP-LINK AC 600 (t2U nano) + wifi driver from https://github.com/chris1111/Wireless-USB-Adapter

Works like a dream, waiting for the USB dongle to arrive.
